export enum ToolCategory {
  DATABASE_CRUD = 'DATABASE_CRUD',
  ACTION = 'ACTION',
  WORKFLOW = 'WORKFLOW',
  METADATA = 'METADATA',
  NATIVE_MODEL = 'NATIVE_MODEL',
  VIEW = 'VIEW',
  VIEW_FIELD = 'VIEW_FIELD',
  VIEW_FILTER = 'VIEW_FILTER',
  VIEW_SORT = 'VIEW_SORT',
  DASHBOARD = 'DASHBOARD',
  LOGIC_FUNCTION = 'LOGIC_FUNCTION',
}
